import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from 'components/Navbar';
import TitleSection from 'components/TitleSection';
import OverviewSection from 'components/OverviewSection'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={ styles.navbar }>
        <Navbar />
      </header>
      <main>
        <TitleSection />
        <OverviewSection />
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </>
  )
}

export default Home
